parameters:
  - name: deployFromFeature
    type: boolean
    default: false
  - name: program
    type: string
  - name: service
    type: string
  - name: resource
    type: string

extends:
  template: /.azuredevops/templates/services-infra-template.yaml
  parameters:
    environments: 
      - name: 'snd1'
        serviceConnection: AZD-ADP-SND1
        deploymentBranches:
          - 'refs/heads/main'
        developmentEnvironment: true
        azureRegions:
          primary: 'UKSouth'
      # - name: 'prd1'
      #   serviceConnection: AZR-ADP-PRD1
      #   deploymentBranches:
      #     - 'refs/heads/main'
      #   azureRegions:
      #     primary: 'UKSouth'
    deployFromFeature: ${{ parameters.deployFromFeature }}
    program: ${{ parameters.program }}
    service: ${{ parameters.service }}
    resource: ${{ parameters.resource }}